# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import multiplication_pb2 as multiplication__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in multiplication_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MultiplicationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMultiplier = channel.unary_unary(
                '/multiplication.Multiplication/GetMultiplier',
                request_serializer=multiplication__pb2.Point.SerializeToString,
                response_deserializer=multiplication__pb2.Multiplier.FromString,
                _registered_method=True)
        self.ListMultipliers = channel.unary_stream(
                '/multiplication.Multiplication/ListMultipliers',
                request_serializer=multiplication__pb2.Rectangle.SerializeToString,
                response_deserializer=multiplication__pb2.Multiplier.FromString,
                _registered_method=True)
        self.RecordMultiplication = channel.stream_unary(
                '/multiplication.Multiplication/RecordMultiplication',
                request_serializer=multiplication__pb2.Point.SerializeToString,
                response_deserializer=multiplication__pb2.MultiplicationSummary.FromString,
                _registered_method=True)
        self.MultiplicationChat = channel.stream_stream(
                '/multiplication.Multiplication/MultiplicationChat',
                request_serializer=multiplication__pb2.Multiplier.SerializeToString,
                response_deserializer=multiplication__pb2.Multiplier.FromString,
                _registered_method=True)


class MultiplicationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMultiplier(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMultipliers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordMultiplication(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MultiplicationChat(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MultiplicationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMultiplier': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMultiplier,
                    request_deserializer=multiplication__pb2.Point.FromString,
                    response_serializer=multiplication__pb2.Multiplier.SerializeToString,
            ),
            'ListMultipliers': grpc.unary_stream_rpc_method_handler(
                    servicer.ListMultipliers,
                    request_deserializer=multiplication__pb2.Rectangle.FromString,
                    response_serializer=multiplication__pb2.Multiplier.SerializeToString,
            ),
            'RecordMultiplication': grpc.stream_unary_rpc_method_handler(
                    servicer.RecordMultiplication,
                    request_deserializer=multiplication__pb2.Point.FromString,
                    response_serializer=multiplication__pb2.MultiplicationSummary.SerializeToString,
            ),
            'MultiplicationChat': grpc.stream_stream_rpc_method_handler(
                    servicer.MultiplicationChat,
                    request_deserializer=multiplication__pb2.Multiplier.FromString,
                    response_serializer=multiplication__pb2.Multiplier.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'multiplication.Multiplication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('multiplication.Multiplication', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Multiplication(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMultiplier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/multiplication.Multiplication/GetMultiplier',
            multiplication__pb2.Point.SerializeToString,
            multiplication__pb2.Multiplier.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMultipliers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/multiplication.Multiplication/ListMultipliers',
            multiplication__pb2.Rectangle.SerializeToString,
            multiplication__pb2.Multiplier.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordMultiplication(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/multiplication.Multiplication/RecordMultiplication',
            multiplication__pb2.Point.SerializeToString,
            multiplication__pb2.MultiplicationSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MultiplicationChat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multiplication.Multiplication/MultiplicationChat',
            multiplication__pb2.Multiplier.SerializeToString,
            multiplication__pb2.Multiplier.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
