# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: multiplication.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'multiplication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14multiplication.proto\x12\x0emultiplication\"\x17\n\x05Point\x12\x0e\n\x06number\x18\x01 \x01(\x05\"3\n\nMultiplier\x12%\n\x06number\x18\x01 \x01(\x0b\x32\x15.multiplication.Point\"Q\n\tRectangle\x12!\n\x02lo\x18\x01 \x01(\x0b\x32\x15.multiplication.Point\x12!\n\x02hi\x18\x02 \x01(\x0b\x32\x15.multiplication.Point\"x\n\x15MultiplicationSummary\x12\x13\n\x0bpoint_count\x18\x01 \x01(\x05\x12\x15\n\rfeature_count\x18\x02 \x01(\x05\x12\x1d\n\x15multiplication_result\x18\x03 \x01(\x03\x12\x14\n\x0c\x65lapsed_time\x18\x04 \x01(\x05\x32\xca\x02\n\x0eMultiplication\x12\x42\n\rGetMultiplier\x12\x15.multiplication.Point\x1a\x1a.multiplication.Multiplier\x12J\n\x0fListMultipliers\x12\x19.multiplication.Rectangle\x1a\x1a.multiplication.Multiplier0\x01\x12V\n\x14RecordMultiplication\x12\x15.multiplication.Point\x1a%.multiplication.MultiplicationSummary(\x01\x12P\n\x12MultiplicationChat\x12\x1a.multiplication.Multiplier\x1a\x1a.multiplication.Multiplier(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multiplication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POINT']._serialized_start=40
  _globals['_POINT']._serialized_end=63
  _globals['_MULTIPLIER']._serialized_start=65
  _globals['_MULTIPLIER']._serialized_end=116
  _globals['_RECTANGLE']._serialized_start=118
  _globals['_RECTANGLE']._serialized_end=199
  _globals['_MULTIPLICATIONSUMMARY']._serialized_start=201
  _globals['_MULTIPLICATIONSUMMARY']._serialized_end=321
  _globals['_MULTIPLICATION']._serialized_start=324
  _globals['_MULTIPLICATION']._serialized_end=654
# @@protoc_insertion_point(module_scope)
